export function getUserName() {
  const params = new URLSearchParams(window.location.search);
  const usernameParam = params.get("username");
  if (usernameParam) {
    localStorage.setItem("playerName", usernameParam);
    return usernameParam;
  }

  const playerName = localStorage.getItem("playerName");
  if (playerName) {
    return playerName;
  }

  const adjectives = [
    "Speedy",
    "Swift",
    "Fast",
    "Quick",
    "Rapid",
    "Turbo",
    "Zoom",
    "Dash",
    "Flash",
    "Bolt",
    "Nimble",
    "Agile",
    "Fleet",
    "Lively",
    "Dynamic",
    "Vibrant",
    "Energetic",
    "Powerful",
    "Mighty",
    "Brave",
    "Daring",
    "Fearless",
    "Bold",
    "Valiant",
    "Courageous",
    "Heroic",
    "Gallant",
    "Noble",
    "Royal",
    "Elite",
    "Supreme",
    "Ultimate",
    "Prime",
    "Peak",
    "Top",
    "Best",
    "Finest",
    "Greatest",
    "Champion",
    "Victor",
    "Winner",
    "Master",
    "Expert",
    "Ace",
    "Pro",
    "Veteran",
    "Legend",
    "Icon",
    "Star",
    "Superstar",
  ];
  const nouns = [
    "Racer",
    "Driver",
    "Kart",
    "Speedster",
    "Champion",
    "Pro",
    "Master",
    "Legend",
    "Hero",
    "Star",
    "Warrior",
    "Knight",
    "Gladiator",
    "Fighter",
    "Combatant",
    "Contender",
    "Challenger",
    "Rival",
    "Opponent",
    "Adversary",
    "Pilot",
    "Navigator",
    "Captain",
    "Commander",
    "Leader",
    "Chief",
    "Boss",
    "Head",
    "Director",
    "Manager",
    "Expert",
    "Specialist",
    "Professional",
    "Veteran",
    "Virtuoso",
    "Maestro",
    "Guru",
    "Sage",
    "Wizard",
    "Sorcerer",
    "Phoenix",
    "Dragon",
    "Tiger",
    "Lion",
    "Eagle",
    "Hawk",
    "Falcon",
    "Wolf",
    "Panther",
    "Jaguar",
    "Thunder",
    "Lightning",
    "Storm",
    "Hurricane",
    "Tornado",
    "Cyclone",
    "Typhoon",
    "Blizzard",
    "Avalanche",
    "Tsunami",
  ];
  const randomAdjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];

  const username = `${randomAdjective} ${randomNoun}`;
  localStorage.setItem("playerName", username);
  return username;
}
